# name: Release
# on:
#   push:
#     tags:
#       - "*"
    
# jobs:
#   build_and_publish_image:
#     runs-on: ubuntu-latest
#     name: Build Image and Push
#     steps: 
#       - uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         run: docker login -u aarthi31 -p ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Image
#         run: |-
#           docker build . --file Dockerfile -t aarthi31/docker-sample-repo:${{ github.ref }}

#       - name: Push Image to GCR
#         run: |-
#           docker push aarthi31/docker-sample-repo:{{github.ref}}

name: Release
 
on:
  push:
    tags:
      - "*"
 
jobs:
  build_and_publish_image_in_dockerhub:
    runs-on: ubuntu-latest
    name   : Build image and push
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Login to DockerHub
      run: docker login -u aarthi31 -p ${{ secrets.DOCKER_PASSWORD}}
 
    - name: Build and tag Docker image
      run: |
        docker build --file Dockerfile -t aarthi31/docker-sample-repo:${{github.ref_name}} .
    
    - name: Push Docker image to DockerHub
      run: |
        docker push aarthi31/docker-sample-repo:${{github.ref_name}}
 
    - name: Run api application in Docker container
      run: |
        docker run -d -p 8000:8000 aarthi31/docker-sample-repo:${{github.ref_name}}